version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: your_db_name
      POSTGRES_USER: your_db_user
      POSTGRES_PASSWORD: your_db_password

  nats:
    image: nats:latest
    ports:
      - "4222:4222"

  app:
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - nats
